### ISSUE TITLE
国内访问 Dockhub 困难，希望增加国内镜像发布地址

### ISSUE THREAD

**Issue by samchugit** [alibaba/DeepRec#1008]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): N/A
- DeepRec version or commit id: N/A
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A

**Describe the problem**

目前 DeepRec 下载地址从 DockerHub 拉取，国内用户访问困难。希望在国内增加发布地址。

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.

**Comment by candyzone** [comment]
This action is ongoing.
We will mirror release/dev images on alibaba cloud.

**Comment by candyzone** [comment]
@samchugit 
The image address prefix is`deeprec-ai-registry.cn-hangzhou.cr.aliyuncs.com`
Repository list:
```
# DeepRec
deeprec-release
deeprec-build
deeprec-base
deeprec-dev
# DeepRec-extension
extension-release
extension-aimaster-release
extension-operator-release
extension-dev
```
eg: deeprec-ai-registry.cn-hangzhou.cr.aliyuncs.com/alideeprec/deeprec-release:deeprec2402-cpu-py38-ubuntu20.04
