### ISSUE TITLE
the performance in a100 is slower than the nvidia-tensorflow 

### ISSUE THREAD

**Issue by thinking03** [alibaba/DeepRec#105]
env: A100 8gpu  + horovod 
framework: DeepRec1.15.5  vs nvidia-tensorflow 1.15.4
model: transformer + mmoe
result:   DeepRec 1.8s/step,   nv-tf:0.55s/step

**Comment by liutongxuan** [comment]
Duplicate issue as https://github.com/alibaba/DeepRec/issues/110
