### ISSUE TITLE
How to use Dynamic-dimension Embedding Variable?

### ISSUE THREAD

**Issue by fuhailin** [alibaba/DeepRec#11]
Refer to the document of [Dynamic-dim Embedding Variable](https://github.com/alibaba/DeepRec/blob/main/docs/Dynamic-dimension-Embedding-Variable.md), I got that `当使用dynamic dimension embedding variable的时候，在embedding_lookup的时候需要传入blocknum上参数，用来指示每一个特征对应的blocknum`. 

But I am confused about how to assign `blocknum` for every feature when embedding lookup. Could you please provide a minimal example to show how to initialize and look_up Dynamic-dimension Embedding Variable?

**Comment by liutongxuan** [comment]
Please take a look at demo: https://github.com/alibaba/DeepRec/tree/main/modelzoo/features/DynamicDimensionEmbeddingVariable/DIEN

**Comment by YongCHN** [comment]
参考具体的例子：
https://github.com/alibaba/DeepRec/blob/main/modelzoo/features/DynamicDimensionEmbeddingVariable/DIEN/script/model.py#L111
