### ISSUE TITLE
[Memory Optimization][DIEN]After replacing tf.Session() with tf.MonitorTrainingSession(), it take many time to collect info.

### ISSUE THREAD

**Issue by Duyi-Wang** [alibaba/DeepRec#136]
When I replaced tf.Session() with tf.MonitorTrainingSession(), it take too much time on collect info for Memory Optimization at one steps.
After closed Memory Optimization by `export ENABLE_MEMORY_OPTIMIZATION=0`, it's ok.
**Code**
Here is the [full code](https://github.com/changqi1/DeepRec/blob/modelzoo/DIEN-rebuild/modelzoo/DIEN/train.py) of rebuilded DIEN.
**reproduce the issue**
Here is the docker image to reproduce with DeepRec build on commit https://github.com/alibaba/DeepRec/commit/e3f51a3431f8a3cf239b8c0d126f28acf5c40fcf
`docker pull cesg-prc-registry-vpc.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:220328-DIEN-issue`

```
cd /root/modelzoo/DIEN
python train.py --steps 300 --no_eval
```
`START_STATISTIC_STEP ` and `STOP_STATISTIC_STEP` are set to 100 and 200 in the train.py.
I put the DIEN code in the main branch at /root/modelzoo/DIEN-old directory.

**logs** 
`START_STATISTIC_STEP ` and `STOP_STATISTIC_STEP` are set to 100 and 200, and step 193 takes so much time.
If use the default setting(start at 1000,stop and 1100), one step between 1080 to 1095 will take a long time.
```
INFO:tensorflow:loss = 0.92963386, steps = 191 (0.206 sec)
INFO:tensorflow:loss = 0.93619776, steps = 192 (0.206 sec)
INFO:tensorflow:loss = 0.96694994, steps = 193 (370.673 sec)
INFO:tensorflow:loss = 0.93243694, steps = 194 (0.208 sec)
INFO:tensorflow:loss = 0.94905794, steps = 195 (0.210 sec)
INFO:tensorflow:loss = 0.9613142, steps = 196 (0.210 sec)
INFO:tensorflow:loss = 0.96409273, steps = 197 (0.209 sec)
```

**Comment by liutongxuan** [comment]
Fixed by https://github.com/alibaba/DeepRec/pull/140
