### ISSUE TITLE
Unsupport GlobalStep in subclass of ValuePtrBase

### ISSUE THREAD

**Issue by Lihengwannafly** [alibaba/DeepRec#161]
When we save checkpoint, the error `F ./tensorflow/core/framework/embedding/value_ptr.h:256] Unsupport GlobalStep in subclass of ValuePtrBase` occurs.  Because I find that the checkpoint is a temporary file `best_checkpoint/best.data-00000-of-00001.tempstate11898667549733680686`.

**Comment by liutongxuan** [comment]
Whether you a model from a model with global_step in EmbeddingVariable, but there's no such configure in graph.

**Comment by Lihengwannafly** [comment]
> Whether you a model from a model with global_step in EmbeddingVariable, but there's no such configure in graph.

I found that the feature eviction is triggered when saving checkpoint,.Therefore, I try to enable GlobalStepEvict for all embedding variables, and it works. So, is it necessary to enable GlobalStepEvict for all embedding variables?

**Comment by Lihengwannafly** [comment]
It is possible to be a compilation environment, and there is no problem with the official mirror.
