### ISSUE TITLE
[SmartStage] id is bigger than  dest.num_nodes

### ISSUE THREAD

**Issue by duoliduoli** [alibaba/DeepRec#177]
https://github.com/alibaba/DeepRec/blob/083cb5fc5e895e928a7817faa736706b911861dc/tensorflow/core/graph/graph_constructor.cc#L1983
try to use smart stage encounter an error , fix it by change dest.num_nodes() to  dest.num_node_ids()

**Comment by liutongxuan** [comment]
Good catch, can u submit a pull request?
