### ISSUE TITLE
[BUILD] gcc-8.3 build DeepRec fail.

### ISSUE THREAD

**Issue by ProphetPeng** [alibaba/DeepRec#228]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.15.5-deeprec2204u1
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
- CUDA/cuDNN version: cuda11.4
- GPU model and memory:

**Describe the problem**

Build deeprec fail when we use gcc 8.3.1. It triggers gcc 8.3.1 compiler bug.  The error is as follows:

unique_ali_op_ut.h:498:77: internal compiler error: in is_normal_capture_proxy, at cp/lambda.c:292

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

![image](https://user-images.githubusercontent.com/2573025/170181330-613de361-bf1d-4b39-b972-e23b2a95f6b8.png)

**Comment by liutongxuan** [comment]
Same issue when build with GCC 9.1

**Comment by liutongxuan** [comment]
Build pass with GCC8.4.0

**Comment by liutongxuan** [comment]
Fixed: https://github.com/alibaba/DeepRec/pull/227
