### ISSUE TITLE
[Modelzoo] DIN and DIEN perf drop based on r1.15.5-deeprec2201 tag.

### ISSUE THREAD

**Issue by changqi1** [alibaba/DeepRec#44]
Modelzoo perf Test based on `[Release] Update DeepRec release version to 1.15.5+deeprec2201. (#43)`.
Test machines: Alibaba Cloud ECS general purpose instance family with high clock speeds - ecs.hfg7.2xlarge.

Test perf result:

Gstep | WDL | WDL | DLRM | DLRM | DeepFM | DeepFM | DSSM | DSSM | DIEN | DIEN | DIN | DIN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
/ | value | percent | value | percent | value | percent | value | percent | value | percent | value | percent
Commuty TF | 31.92626 | baseline | 82.09168 | baseline | 37.20978 | baseline | 18.54726 | baseline | 14.62987 | baseline | 18.57746 | baseline
DeepRec FP32 | 34.69318 | 108.67% | 105.4547 | 128.46% | 43.31713 | 116.41% | 21.64175 | 116.68% | 13.27125 | **90.71%** | 17.6932 | **95.24%**
DeepRec BF16 | 49.38222 | 154.68% | 114.2221 | 139.14% | 47.34401 | 127.24% | 23.13698 | 124.75% | 13.0392 | **89.13%** | 17.20525 | **92.61%**

Test AUC result:

AUC | WDL | WDL | DLRM | DLRM | DeepFM | DeepFM | DSSM | DSSM | DIEN | DIEN | DIN | DIN
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
/ | value | percent | value | percent | value | percent | value | percent | value | percent | value | percent
Commuty TF | 0.775168 | baseline | 0.768852 | baseline | 0.744794 | baseline | 0.504404 | baseline | 0.8443 | baseline | 0.7887 | baseline
DeepRec FP32 | 0.775515 | 100.04% | 0.771128 | 100.30% | 0.746055 | 100.17% | 0.503653 | 99.85% | 0.8472 | 100.34% | 0.7913 | 100.33%
DeepRec BF16 | 0.77604 | 100.11% | 0.772185 | 100.43% | 0.741192 | 99.52% | 0.492327 | 97.61% | 0.8358 | 98.99% | 0.7883 | 99.95%

PS: DSSM dataset is small, so its ACC and AUC is limited.

**Comment by heagoo** [comment]
@changqi1 do we have performance analysis data? let's discuss on that.

**Comment by changqi1** [comment]
@pujiang2018  Will collect it.

**Comment by changqi1** [comment]
Update DIN and DIEN AUC and perf data. The issue has been fixed by fusing optimizer.

| AUC | WDL | WDL | DLRM | DLRM | Deep FM | Deep FM | DSSM | DSSM | DIEN | DIEN | DIN  | DIN
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 
| / | value | percent | value | percent | value | percent | value | percent | value | percent | value | percent
| Community TF | 0.775182 | baseline | 0.774829 | baseline | 0.743674 | baseline | 0.503107 | baseline | 0.749009 | baseline | 0.743708 | baseline
| DeepRec FP32 | 0.775283 | 100.01% | 0.766892 | 98.98% | 0.768079 | 103.28% | 0.49983 | 99.35% | 0.749727 | 100.10% | 0.751069 | 100.99%
| DeepRec BF16 | 0.775907 | 100.09% | 0.770136 | 99.39% | 0.771628 | 103.76% | 0.49125 | 97.64% | 0.744693 | 99.42% | 0.749514 | 100.78%

| Gsteps/s | WDL | WDL | DLRM | DLRM | Deep FM | Deep FM | DSSM | DSSM | DIEN | DIEN | DIN  | DIN
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| / | value | percent | value | percent | value | percent | value | percent | value | percent | value | percent
| Community TF | 31.78435 | baseline | 81.4195 | baseline | 37.17086 | baseline | 18.35918 | baseline | 12.39816 | baseline | 30.98243 | baseline
| DeepRec FP32 | 33.09086 | 104.11% | 95.18336 | 116.90% | 61.46826 | 165.37% | 27.89201 | 151.92% | 15.48097 | 124.87% | 117.1144 | 378.00%
| DeepRec BF16 | 47.52758 | 149.53% | 103.9707 | 127.70% | 70.93534 | 190.84% | 30.49329 | 166.09% | 16.04443 | 129.41% | 103.5385 | 334.18%
