### ISSUE TITLE
compile processor failed with config mkl_threadpool 

### ISSUE THREAD

**Issue by xzbcodelife** [alibaba/DeepRec#590]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
   run command ./configure serving --mkl_threadpool on branch deeprec2208,  and then  build processor failed
   
ERROR: /data1/xuzhibin/Deeprec_2208/DeepRec/tensorflow/core/kernels/BUILD:4124:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_matmul_op' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 327 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./tensorflow/core/kernels/mkl_matmul_ops_common.h:28:0,
                 from tensorflow/core/kernels/mkl_matmul_op.cc:33:
./tensorflow/core/util/mkl_util.h: In function 'std::ostream& tensorflow::operator<<(std::ostream&, const tensorflow::MklTensorFormat&)':
./tensorflow/core/util/mkl_util.h:218:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
In file included from tensorflow/core/kernels/mkl_matmul_op.cc:33:0:
./tensorflow/core/kernels/mkl_matmul_ops_common.h: In instantiation of 'void tensorflow::{anonymous}::dnnl_gemm(char, char, int64_t, int64_t, int64_t, float, const T*, int64_t, const T*, int64_t, float, T*, int64_t, tensorflow::OpKernelContext*) [with T = Eigen::bfloat16; int64_t = long int]':
tensorflow/core/kernels/mkl_matmul_op.cc:188:24:   required from 'void tensorflow::MklMatMulOp<Device, T, USE_CUBLAS>::MklBlasGemm(tensorflow::OpKernelContext*, bool, bool, int, int, int, const bfloat16*, int, const bfloat16*, int, tensorflow::bfloat16*, int) [with Device = Eigen::ThreadPoolDevice; T = Eigen::bfloat16; bool USE_CUBLAS = false; tensorflow::bfloat16 = Eigen::bfloat16]'
tensorflow/core/kernels/mkl_matmul_op.cc:98:16:   required from 'void tensorflow::MklMatMulOp<Device, T, USE_CUBLAS>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = Eigen::bfloat16; bool USE_CUBLAS = false]'
tensorflow/core/kernels/mkl_matmul_op.cc:207:1:   required from here
./tensorflow/core/kernels/mkl_matmul_ops_common.h:777:22: error: no matching function for call to 'tensorflow::MklDnnThreadPool::MklDnnThreadPool(tensorflow::OpKernelContext*&, int)'
     MklDnnThreadPool eigen_tp(ctx, 1);
                      ^~~~~~~~
In file included from ./tensorflow/core/util/mkl_util.h:39:0,
                 from ./tensorflow/core/kernels/mkl_matmul_ops_common.h:28,
                 from tensorflow/core/kernels/mkl_matmul_op.cc:33:
./tensorflow/core/util/mkl_threadpool.h:145:3: note: candidate: tensorflow::MklDnnThreadPool::MklDnnThreadPool(tensorflow::OpKernelContext*)
   MklDnnThreadPool(OpKernelContext* ctx) {}
   ^~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_threadpool.h:145:3: note:   candidate expects 1 argument, 2 provided
./tensorflow/core/util/mkl_threadpool.h:144:3: note: candidate: constexpr tensorflow::MklDnnThreadPool::MklDnnThreadPool()
   MklDnnThreadPool() = default;
   ^~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_threadpool.h:144:3: note:   candidate expects 0 arguments, 2 provided
./tensorflow/core/util/mkl_threadpool.h:143:8: note: candidate: constexpr tensorflow::MklDnnThreadPool::MklDnnThreadPool(const tensorflow::MklDnnThreadPool&)
 struct MklDnnThreadPool {
        ^~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_threadpool.h:143:8: note:   candidate expects 1 argument, 2 provided
./tensorflow/core/util/mkl_threadpool.h:143:8: note: candidate: constexpr tensorflow::MklDnnThreadPool::MklDnnThreadPool(tensorflow::MklDnnThreadPool&&)
./tensorflow/core/util/mkl_threadpool.h:143:8: note:   candidate expects 1 argument, 2 provided
In file included from tensorflow/core/kernels/mkl_matmul_op.cc:33:0:
./tensorflow/core/kernels/mkl_matmul_ops_common.h: At global scope:
./tensorflow/core/kernels/mkl_matmul_ops_common.h:565:8: warning: 'void tensorflow::{anonymous}::MklMatMulPrimitive<T>::Execute(const T*, const T*, T*, std::shared_ptr<dnnl::stream>) [with T = Eigen::bfloat16]' used but never defined
   void Execute(const T* a_data, const T* b_data, T* c_data,
        ^~~~~~~
In file included from ./tensorflow/core/kernels/mkl_matmul_ops_common.h:28:0,
                 from tensorflow/core/kernels/mkl_matmul_op.cc:33:
./tensorflow/core/util/mkl_util.h:994:19: warning: 'dnnl::memory::data_type tensorflow::MklDnnType() [with T = Eigen::QInt32]' defined but not used [-Wunused-function]
 memory::data_type MklDnnType<qint32>() {
                   ^~~~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_util.h:989:19: warning: 'dnnl::memory::data_type tensorflow::MklDnnType() [with T = Eigen::QInt8]' defined but not used [-Wunused-function]
 memory::data_type MklDnnType<qint8>() {
                   ^~~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_util.h:984:19: warning: 'dnnl::memory::data_type tensorflow::MklDnnType() [with T = unsigned char]' defined but not used [-Wunused-function]
 memory::data_type MklDnnType<uint8>() {
                   ^~~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_util.h:979:19: warning: 'dnnl::memory::data_type tensorflow::MklDnnType() [with T = Eigen::QUInt8]' defined but not used [-Wunused-function]
 memory::data_type MklDnnType<quint8>() {
                   ^~~~~~~~~~~~~~~~~~
./tensorflow/core/util/mkl_util.h:974:19: warning: 'dnnl::memory::data_type tensorflow::MklDnnType() [with T = float]' defined but not used [-Wunused-function]
 memory::data_type MklDnnType<float>() {
                   ^~~~~~~~~~~~~~~~~
In file included from ./tensorflow/core/util/mkl_util.h:31:0,
                 from ./tensorflow/core/kernels/mkl_matmul_ops_common.h:28,
                 from tensorflow/core/kernels/mkl_matmul_op.cc:33:
./tensorflow/core/graph/mkl_graph_util.h:115:20: warning: 'tensorflow::mkl_op_registry::kMklQuantizedOpLabel' defined but not used [-Wunused-variable]
 static const char* kMklQuantizedOpLabel = "QuantizedMklOp";
                    ^~~~~~~~~~~~~~~~~~~~
./tensorflow/core/graph/mkl_graph_util.h:104:20: warning: 'tensorflow::mkl_op_registry::kMklLayoutDependentOpLabel' defined but not used [-Wunused-variable]
 static const char* kMklLayoutDependentOpLabel = "MklLayoutDependentOp";
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
Target //serving/processor/serving:libserving_processor.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 409.028s, Critical Path: 131.40s
INFO: 1829 processes: 2 local, 1827 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

![1670902435424_665AC04E-23B0-4784-BD7B-D2958880843D](https://user-images.githubusercontent.com/42902396/207220221-1857316f-551a-4d89-8b32-f4cc67e7e779.png)

**Comment by changqi1** [comment]
Fixed. https://github.com/alibaba/DeepRec/pull/593
