### ISSUE TITLE
EV Initializer的使用案例文档编写异常

### ISSUE THREAD

**Issue by a1164714** [alibaba/DeepRec#769]
地址：https://deeprec.readthedocs.io/zh/latest/Embedding-Variable.html#id4
现象：
![image](https://user-images.githubusercontent.com/20268814/226510696-0d6aaed6-2357-4f7d-b1ee-e01a5bed35c4.png)

请问变量名是否设置错误了？

**Comment by liutongxuan** [comment]
是的，欢迎提一个PR来修复一下。

**Comment by a1164714** [comment]
已提交PR https://github.com/alibaba/DeepRec/pull/772

**Comment by liutongxuan** [comment]
Done
