### ISSUE TITLE
Docker container cannot run python scripts with tensorflow imported.

### ISSUE THREAD

**Issue by spongezz** [alibaba/DeepRec#785]
OS: ubuntu 20.04
CPU: 12th Gen Intel(R) Core(TM) i7-12700K
GPU: RTX 3060

When I enter the docker environment of alideeprec/deeprec-release-modelzoo:latest and run python train.py in DCN, it reports Illegal instruction (core dumped). If I use python command line, I can import numpy but as soon as I import tensorflow, the same error occurs. I searched the Internet and found the reason maybe my cpu does not support AVX but it does support AVX. Can you help me solve the problem? Thank you!

**Comment by liutongxuan** [comment]
Release images are built on "Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz". For your CPU, you can't run because your CPU can't support advanced instructions. You have to build DeepRec yourself on your CPU.

**Comment by spongezz** [comment]
> 

My bad. Thank you!
